/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Categoria;
import Logica.Fabrica;
import Logica.IControladorPedido;
import Logica.IControladorProducto;
import Logica.IControladorUsuario;
import Logica.ManejadorProducto;
import Logica.ManejadorUsuario;
import Logica.Producto;
import Logica.Restaurante;
import Logica.Usuario;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.SortedSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class RegistrarProducto extends javax.swing.JInternalFrame {
   
    private IControladorProducto ICP;
    
    public void ocultar(){
    
        this.txtNombre.setVisible(false);
        this.txtDescripcion.setVisible(false);
        this.txtPrecio.setVisible(false);
        this.Nombre.setVisible(false);
        this.Descripcion.setVisible(false);
        this.Precio.setVisible(false);
        this.LabelImagen.setVisible(false);
        this.SeleccionarImagen.setVisible(false);
        this.Promocion.setVisible(false);
        this.Individual.setVisible(false);
        this.SeleccioneProducto.setVisible(false);
        this.Productos.setVisible(false);
        this.Cant.setVisible(false);
        this.Cantidad.setVisible(false);
        this.Agregar.setVisible(false);
        this.tablaProducto.setVisible(false);
        this.Registrar.setVisible(false);
        this.scrollProducto.setVisible(false);
        
    }
    public void comboboxRestaurante(){
          //PARA CARGAR COMBOBOX DE RESTARUANTES
        ManejadorUsuario MU = ManejadorUsuario.getinstance();            
        Map ColRest= MU.getColeccionRestaurante();
        int posicion=0;
        Iterator<Usuario> it = ColRest.values().iterator();
            Usuario Rest=null;
            String a=(String) SelectRestaurante.getItemAt(0);
            if(a==null){
                while (it.hasNext()) {
                    Rest=it.next();
                    SelectRestaurante.insertItemAt(Rest.getnickname(), posicion);
                    posicion++;
                }
            }    
    }
           
    public RegistrarProducto() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICP = fabrica.getIControladorProducto();
        ocultar();
        comboboxRestaurante();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botonoes = new javax.swing.ButtonGroup();
        IngreseDatosCliente = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        LabelImagen = new javax.swing.JLabel();
        SeleccionarImagen = new javax.swing.JButton();
        Individual = new javax.swing.JRadioButton();
        Promocion = new javax.swing.JRadioButton();
        Productos = new javax.swing.JComboBox();
        SeleccioneProducto = new javax.swing.JLabel();
        Cant = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Cantidad = new javax.swing.JSpinner();
        Restaurante = new javax.swing.JLabel();
        SelectRestaurante = new javax.swing.JComboBox();
        scrollProducto = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        IngreseDatosCliente.setText("Ingrese los siguientes datos:");

        Descripcion.setText("Descripcion");

        Nombre.setText("Nombre");

        Precio.setText("Precio");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        LabelImagen.setText("Imagen");
        LabelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SeleccionarImagen.setText("Seleccionar Imagen");
        SeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarImagenActionPerformed(evt);
            }
        });

        Botonoes.add(Individual);
        Individual.setText("Individual");
        Individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualActionPerformed(evt);
            }
        });

        Botonoes.add(Promocion);
        Promocion.setText("Promocion");
        Promocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromocionActionPerformed(evt);
            }
        });

        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        SeleccioneProducto.setText("Producto");

        Cant.setText("Cantidad");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        Cantidad.setAutoscrolls(true);

        Restaurante.setText("Restaurante:");

        SelectRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRestauranteActionPerformed(evt);
            }
        });

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollProducto.setViewportView(tablaProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngreseDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Individual)
                                .addGap(18, 18, 18)
                                .addComponent(Promocion)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Agregar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Registrar))
                                    .addComponent(scrollProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SeleccioneProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cant, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SeleccionarImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IngreseDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Individual))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Promocion)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeleccionarImagen)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cant)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccioneProducto))
                .addGap(23, 23, 23)
                .addComponent(Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar)
                    .addComponent(Registrar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       
        this.dispose();
       
    }//GEN-LAST:event_CancelarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        ManejadorProducto MP = ManejadorProducto.getinstance();
               
        if(!this.Individual.isSelected() && (!this.Promocion.isSelected())){
            JOptionPane.showMessageDialog(this,"Seleccione si el producto es individual o promocion","REGISTRO",JOptionPane.WARNING_MESSAGE);
            Individual.requestFocus();
        }
        if(this.Promocion.isSelected()){
            if(this.Productos.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(this,"Seleccione algun producto","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtNombre.requestFocus();
            }
            if(this.txtNombre.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Ingrese el nombre","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtNombre.requestFocus();
            }else if(this.txtDescripcion.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Ingrese descripcion","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtDescripcion.requestFocus();
            }else {
                String nombreRestaurante=(String) SelectRestaurante.getSelectedItem();
                ManejadorUsuario MU = ManejadorUsuario.getinstance();
                Restaurante rest = MU.findRestaurante(nombreRestaurante);
                if (rest.verificarproducto(txtNombre.getText())){
                    JOptionPane.showMessageDialog(this,"La Promocion ya existe","REGISTRO",JOptionPane.WARNING_MESSAGE);
                    txtNombre.requestFocus();
                }
                else{
                ICP.AltaProductoPromocion(rest,txtNombre.getText(),txtDescripcion.getText(), preciototal, true, 0, coleccionProductosAgregar);
                JOptionPane.showMessageDialog(this,"Promocion ingresada con Exito","REGISTRO",JOptionPane.INFORMATION_MESSAGE);
                dispose();
                }
            }            
        } 
        else if (this.Individual.isSelected()) {
            if(this.txtNombre.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Ingrese el nombre","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtNombre.requestFocus();
            }else if(this.txtDescripcion.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Ingrese descripcion","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtDescripcion.requestFocus();
            }else if(this.txtPrecio.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Ingrese el precio","REGISTRO",JOptionPane.WARNING_MESSAGE);
                txtPrecio.requestFocus();
            }else {
                //(String) castea el valor seleccionado a tipo string 
                String nombreRestaurante=(String) SelectRestaurante.getSelectedItem();
                ManejadorUsuario MU = ManejadorUsuario.getinstance();
                Restaurante rest = MU.findRestaurante(nombreRestaurante);
                if (rest.verificarproducto(txtNombre.getText())){
                    JOptionPane.showMessageDialog(this,"El Producto ya existe","REGISTRO",JOptionPane.WARNING_MESSAGE);
                    txtNombre.requestFocus();
                }
                else{    
                    double precio = Double.parseDouble(txtPrecio.getText());
                    ICP.AltaProductoIndividual(rest,txtNombre.getText(),txtDescripcion.getText(),precio);
                    JOptionPane.showMessageDialog(this,"Producto ingresado con Exito","REGISTRO",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        }
        
    }//GEN-LAST:event_RegistrarActionPerformed

    File fichero;
    private void SeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarImagenActionPerformed
        // TODO add your handling code here:
        int resultado;

        CargarFoto ventana = new CargarFoto();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        ventana.FileChooser.setFileFilter(filtro);
        resultado= ventana.FileChooser.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado){
            fichero = ventana.FileChooser.getSelectedFile();
            try{
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(LabelImagen.getWidth(), LabelImagen.getHeight(), Image.SCALE_DEFAULT));
                LabelImagen.setText(null);
                LabelImagen.setIcon( icono );

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);
            }
        }
    }//GEN-LAST:event_SeleccionarImagenActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosActionPerformed

    private void IndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualActionPerformed
        
        this.txtNombre.setVisible(true);
        this.txtDescripcion.setVisible(true);
        this.txtPrecio.setVisible(true);
        this.Nombre.setVisible(true);
        this.Descripcion.setVisible(true);
        this.Precio.setVisible(true);
        this.LabelImagen.setVisible(true);
        this.SeleccionarImagen.setVisible(true);
        this.Registrar.setVisible(true);
    }//GEN-LAST:event_IndividualActionPerformed

    private void PromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromocionActionPerformed
        
        this.Nombre.setVisible(true);
        this.txtNombre.setVisible(true);
        this.Descripcion.setVisible(true);
        this.txtDescripcion.setVisible(true);
        this.SeleccioneProducto.setVisible(true);
        this.Productos.setVisible(true);
        this.Cant.setVisible(true);
        this.Cantidad.setVisible(true);
        this.Agregar.setVisible(true);
        this.tablaProducto.setVisible(true);
        this.scrollProducto.setVisible(true);
        this.Registrar.setVisible(true);
        
         //PARA CARGAR COMBOBOX DE PRDUCTOS
        String nombreRestaurante=(String) SelectRestaurante.getSelectedItem();
        ManejadorUsuario MU = ManejadorUsuario.getinstance();  
        Map ColeccionProducto = MU.getColeccionProductosRestaurantes(nombreRestaurante);
        Iterator<Producto> itProducto = ColeccionProducto.values().iterator();
            Producto prod=null;
            String b=(String) Productos.getItemAt(0);
            if(b==null){
                while (itProducto.hasNext()) {
                    prod=itProducto.next();
                    Productos.addItem(prod.getnombre());  
                }
            } 
    }//GEN-LAST:event_PromocionActionPerformed

    private void SelectRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRestauranteActionPerformed
        // TODO add your handling code here:
        if(this.SelectRestaurante.getSelectedIndex() != -1){
            
            this.Promocion.setVisible(true);
            this.Individual.setVisible(true);
            
        }
    }//GEN-LAST:event_SelectRestauranteActionPerformed
    int fila=0;
    //VARIABLE GLOBAL PARA SUMAR LOS SUBTOTALES DE LA TABLA Y
    //LUEGO PASARLO A LA FUNCION DE AGREGAR PROMO
    double preciototal=0;
    Map<String,Producto> coleccionProductosAgregar=new HashMap<String,Producto>();
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        ManejadorUsuario MU= ManejadorUsuario.getinstance();
        
        //AGREGAR FILAS A LA TABLA
        DefaultTableModel modelo= (DefaultTableModel) this.tablaProducto.getModel();
        int columna = modelo.getColumnCount();
        modelo.addRow(new Object[columna]);
        tablaProducto.setModel(modelo);
            //OBTENGO NOM DE RESTAURANTE Y PRODUCTO
        String nombreRestaurante=(String) SelectRestaurante.getSelectedItem();
        String nombreProducto=(String) Productos.getSelectedItem();
        double precio=MU.buscarprecioproducto(nombreRestaurante,nombreProducto);
        //AGREGO VALORES A  LAS FILAS
        tablaProducto.setValueAt(Productos.getSelectedItem(), fila, 0);
        tablaProducto.setValueAt(Cantidad.getValue(), fila, 1);
            //CALCULO EL TOTAL
        int cantidad=(int) Cantidad.getValue();
        double total=(precio * cantidad);
        tablaProducto.setValueAt(total, fila, 2);
        //AGREGO VALOR A LAS VARIABLES GLOBALES QUE PASO A LA FUNCION DE ALTAPROMOCION
        preciototal=preciototal+total;
        Producto pro=MU.getProductoRestaurante(nombreRestaurante, nombreProducto);
        coleccionProductosAgregar.put(nombreProducto, pro);
        fila++;     
    }//GEN-LAST:event_AgregarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Agregar;
    private javax.swing.ButtonGroup Botonoes;
    private javax.swing.JButton Cancelar;
    public javax.swing.JLabel Cant;
    public javax.swing.JSpinner Cantidad;
    public javax.swing.JLabel Descripcion;
    public javax.swing.JRadioButton Individual;
    private javax.swing.JLabel IngreseDatosCliente;
    public javax.swing.JLabel LabelImagen;
    public javax.swing.JLabel Nombre;
    public javax.swing.JLabel Precio;
    public javax.swing.JComboBox Productos;
    public javax.swing.JRadioButton Promocion;
    public javax.swing.JButton Registrar;
    private javax.swing.JLabel Restaurante;
    public javax.swing.JButton SeleccionarImagen;
    public javax.swing.JLabel SeleccioneProducto;
    public javax.swing.JComboBox SelectRestaurante;
    private javax.swing.JScrollPane scrollProducto;
    private javax.swing.JTable tablaProducto;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
